### ISSUE TITLE
Rotate recovery can't rotate in place because there is a potential collision. Cost: -1.00

### ISSUE THREAD

**Issue by huangju91** [paulbovbel/frontier_exploration#27]
At the start, the robot explores well ,but it stop after  errors" Rotate recovery can't rotate in place because there is a potential collision" "Aborting because a valid plan could not be found. Even after executing all recovery behaviors" appeared.
"

**Comment by paulbovbel** [comment]
This a system problem, and not specifically a frontier_exploration implementation issue. Please post on ROS Answers.
